name: Windows2

on:
   push:
      branches: [ RC_1_2 RC_2_0 master ]
   pull_request:

defaults:
   run:
      shell: cmd

jobs:
   build:
      name: Build
      runs-on: windows-2019

      strategy:
         matrix:
           include:
             - config: asio-debugging=on picker-debugging=on windows-version=vista
             - config: windows-api=store windows-version=win10
             - config: deprecated-functions=off

      steps:
      - name: checkout
        uses: actions/checkout@v2.3.3
        with:
           submodules: true

      - name: install boost
        run: |
          git clone --depth=1 --recurse-submodules -j10 --branch=boost-1.78.0 https://github.com/boostorg/boost.git
          cd boost
          bootstrap.bat

      - name: install openssl (64 bit)
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 30
          retry_wait_seconds: 4
          max_attempts: 3
          command: choco install openssl --limitoutput --no-progress

      - name: boost headers
        run: |
          cd boost
          .\b2 headers

      - name: build library
        run: |
          set BOOST_ROOT=%CD%\boost
          set PATH=%BOOST_ROOT%;%PATH%
          b2 ${{ matrix.config }} cxxstd=14 address-model=64 warnings=all warnings-as-errors=on

      - name: build examples
        if: ${{ ! contains(matrix.config, 'windows-api=store') }}
        run: |
          set BOOST_ROOT=%CD%\boost
          set PATH=%BOOST_ROOT%;%PATH%
          cd examples
          b2 ${{ matrix.config }} address-model=64 warnings=all warnings-as-errors=on

      - name: build tools
        if: ${{ ! contains(matrix.config, 'windows-api=store') }}
        run: |
          set BOOST_ROOT=%CD%\boost
          set PATH=%BOOST_ROOT%;%PATH%
          cd tools
          b2 ${{ matrix.config }} address-model=64 warnings=all warnings-as-errors=on
      
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: examples


